### ISSUE TITLE
#database

### ISSUE THREAD

**Issue by aldisahabi01** [Alexsey272/Anon-Plaid#2]
is the database not working?try to see this to create without database👇
https://github.com/gigstate/tg-chat-bot

**Comment by Alexsey272** [comment]
the database is working, just before using it, you need to specify at least one administrator in the "admins" table
--
Отправлено из VK Почта для Android суббота, 27 ноября 2021г., 23:32 +07:00 от aldisahabi01  ***@***.*** :
